# Generated by Django 2.1.1 on 2021-08-12 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20210812_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=24)),
                ('contact', models.CharField(blank=True, max_length=24)),
                ('phone', models.CharField(default=False, max_length=11)),
                ('deposit', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('days', models.CharField(blank=True, max_length=100)),
                ('balance', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_Order_Customer', to='customer.CustomerModel')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
