# Generated by Django 2.1.1 on 2021-08-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210812_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='created',
            new_name='orderdate',
        ),
    ]
