# Generated by Django 2.1.1 on 2021-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210812_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='days',
            field=models.PositiveSmallIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
