# Generated by Django 2.1.1 on 2021-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210812_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='days',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
