# Generated by Django 2.1.1 on 2021-08-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210812_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='days',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
