# Generated by Django 2.1.1 on 2021-08-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210814_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_Order_Customer', to='customer.CustomerModel'),
        ),
    ]
