# Generated by Django 2.1.1 on 2021-08-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210814_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
