# Generated by Django 2.1.1 on 2021-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210814_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='effectdays',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
