# Generated by Django 2.1.1 on 2021-08-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='contact',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(default=False, max_length=11),
        ),
    ]
