# Generated by Django 2.1.1 on 2021-08-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='customer',
            new_name='name',
        ),
    ]
