# Generated by Django 2.1.1 on 2021-08-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210812_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='contact',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
